### ISSUE TITLE
Unify Coding Styles and Tools

### ISSUE THREAD

**Issue by jetjinser** [nonedesktop/Nonebot-Desktop-Qt#6]
### Description
Inconsistent coding styles and different development tools are causing issues in the project (in the future). To improve code quality and collaboration, we need to unify the coding styles and tools used.

### Goal
Standardize the code style and the use of development tools.

### Plan
1. Assess existing code styles and create a unified code style guideline.
2. Evaluate development tools and recommend standardized tools.
3. Team unification on new coding style and tooling.

### Outcome
Improved code quality, easier collaboration, and increased efficiency.

**Comment by jetjinser** [comment]
For reference, the tools I'm currently using:
- package manager: `rye`
- linter: `ruff`
- formatter: `black` (google code style)
- type checker: `pyright`

<details>
  <summary>Full pyproject.toml</summary>

  ```toml
  [project]
  name = "nonebot-desktop-qt"
  version = "0.1.0"
  description = "Add your description here"
  authors = [
      { name = "Jinser", email = "cmdr.jv@gmail.com" }
  ]
  dependencies = [
      "PySide6-Fluent-Widgets>=0.9.10",
      "pydantic>=1.10, <2",
      "nonebot-desktop-wing>=0.2.8",
  ]
  readme = "README.md"
  requires-python = ">= 3.10"
  
  [build-system]
  requires = ["hatchling"]
  build-backend = "hatchling.build"
  
  [tool.rye]
  managed = true
  dev-dependencies = [
      "pyright>=1.1.317",
      "black>=23.7.0",
      "ruff>=0.0.278",
  ]
  
  [tool.hatch.metadata]
  allow-direct-references = true
  
  [tool.ruff]
  line-length = 92
  
  [tool.rye.scripts]
  app = { cmd = ["python", "app/main.py"] }
  playground = { cmd = ["python", "app/playground.py"] }
  ```
</details>
